### PR TITLE
add macosx supports

### PR DESCRIPTION
**Pull request by ba0f3**
not sure if it works correctly

### CODE REVIEW

**Comment by ivankoster** [comment]
Please implement the 2 comments and I will merge it :)

**Comment by ba0f3** [comment]
fixed :wink:

**Comment by oderwat** [comment]
ty both! will test it on osx later today :)

**Comment by ivankoster** [comment]
@oderwat I'm hopeful it works. The doNotOptimizeAway function seems pretty portable. I played around a bit with nimbench on mingw gcc on windows yesterday and I get correct results.
doNotOptimizeAway can possibly be improved even for gcc/clang, with some inline assembly it doesn't even have to be a function call. But for now the current implementation seems a good portable baseline.

**Comment by ivankoster** [comment]
@oderwat Is it working correctly on OSX? Please let me know!

**Pull request merged**
